TRIREX_SYSTEM_MSG = (f"Instructions for converting Wikidata Knowledge-Base Triples (Subject, Predicate, Object) "
                     f"into accurate and coherent human-readable sentences: It's crucial to preserve the "
                     f"original meaning and direction of the Predicate in the sentence. Do not reverse or "
                     f"misinterpret the relationship implied by the Predicate. For instance, 'owned by' should "
                     f"not be converted to 'owns'. The output sentence must reflect the exact relationship as "
                     f"stated in the Triple, with the Subject and Object maintaining their original roles."
                     f"SENTENCES MUST START WITH THE SUBJECT AND END WITH THE OBJECT!!!\n"
                     f"\n"
                     f"Correct Usage Examples:\n"
                     f"\n"
                     f"Subject: 'The Mona Lisa'\n"
                     f"Predicate: 'owned by'\n"
                     f"Object: 'The Louvre Museum'\n"
                     f"Output: 'The Mona Lisa is owned by The Louvre Museum.'\n"
                     f"(Note: The direction of ownership is correctly maintained from 'The Mona Lisa' to 'The Louvre Museum')\n"
                     f"\n"
                     f"Subject: 'Serena Williams'\n"
                     f"Predicate: 'sibling of'\n"
                     f"Object: 'Venus Williams'\n"
                     f"Output: 'Serena Williams is a sibling of Venus Williams.'\n"
                     f"\n"
                     f"Subject: 'Angelina Jolie'\n"
                     f"Predicate: 'parent of'\n"
                     f"Object: 'Shiloh Jolie-Pitt'\n"
                     f"Output: 'Angelina Jolie is a parent of Shiloh Jolie-Pitt.'\n"
                     f"\n"
                     f"Subject: 'Pixar'\n"
                     f"Predicate: 'subsidiary of'\n"
                     f"Object: 'The Walt Disney Company'\n"
                     f"Output: 'Pixar is a subsidiary of The Walt Disney Company.'\n"
                     f"\n"
                     f"Subject: 'COVID-19'\n"
                     f"Predicate: 'caused by'\n"
                     f"Object: 'SARS-CoV-2'\n"
                     f"Output: 'COVID-19 is caused by SARS-CoV-2.'\n"
                     f"\n"
                     f"Subject: 'The Eiffel Tower'\n"
                     f"Predicate: 'located in'\n"
                     f"Object: 'Paris'\n"
                     f"Output: 'The Eiffel Tower is located in Paris.'\n"
                     f"\n"
                     f"Subject: 'George W. Bush'\n"
                     f"Predicate: 'predecessor of'\n"
                     f"Object: 'Barack Obama'\n"
                     f"Output: 'George W. Bush is the predecessor of Barack Obama.'\n"
                     f"\n"
                     f"Subject: 'The sky'\n"
                     f"Predicate: 'color of'\n"
                     f"Object: 'blue'\n"
                     f"Output: 'The sky is blue in color.'\n"
                     f"\n"
                     f"Subject: '1984'\n"
                     f"Predicate: 'theme of'\n"
                     f"Object: 'totalitarianism'\n"
                     f"Output: 'Totalitarianism is a theme of 1984.'\n"
                     f"\n"
                     f"Subject: 'Heart'\n"
                     f"Predicate: 'function of'\n"
                     f"Object: 'pumping blood'\n"
                     f"Output: 'The function of the heart is pumping blood.'\n"
                     f"\n"
                     f"Subject: 'The Starry Night'\n"
                     f"Predicate: 'painted by'\n"
                     f"Object: 'Vincent van Gogh'\n"
                     f"Output: 'The Starry Night was painted by Vincent van Gogh.'\n"
                     f"(Note: The relationship correctly indicates that 'The Starry Night' is the work created by Vincent van Gogh)\n"
                     f"\n"
                     f"Subject: 'Symphony No. 5'\n"
                     f"Predicate: 'composed by'\n"
                     f"Object: 'Ludwig van Beethoven'\n"
                     f"Output: 'Symphony No. 5 was composed by Ludwig van Beethoven.'\n"
                     f"(Note: This maintains the direction of the composition relationship from 'Symphony No. 5' to 'Ludwig van Beethoven')\n"
                     f"\n")

def triple_to_trirex_prompt(subject, predicate, object_):
    return (f"{TRIREX_SYSTEM_MSG}"
            f"Subject: '{subject}'\n"
            f"Predicate: '{predicate}'\n"
            f"Object: '{object_}'\n"
            f"Output: '")
